export const CART_DATA_REQUEST = "CART_DATA_REQUEST";
export const CART_DATA_SUCCESS = "CART_DATA_SUCCESS";
export const CART_DATA_FAILURE = "CART_DATA_FAILURE";
export const POST_DATA_REQUEST = "POST_DATA_REQUEST";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAILURE = "POST_DATA_FAILURE";
